### ISSUE TITLE
Fetch schema.org data from DRUM

### ISSUE THREAD

**Issue by ghost** [wallberg/linked-data-sandbox#1]
Fetch schema.org data (serialized as json-ld) in DRUM's UMD Data Collection, http://hdl.handle.net/1903/27670

**Comment by ghost** [comment]
JSON-LD embedded in HTML is not yet supported, see:

- https://github.com/RDFLib/rdflib-jsonld/issues/62
- https://github.com/RDFLib/rdflib-jsonld/pull/63

**Comment by wallberg** [comment]
JSON-LD is now supported in RDFLib 7.1.0 via https://github.com/RDFLib/rdflib/pull/2804
